name: Build CI

on: [push, pull_request] # TODO upadate
jobs:
  clone:
    # separate clone + artifact job because the action wants git 2.18
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: 'recursive'
        path: catkin_ws/src/${{ github.repository }}
    - uses: actions/upload-artifact@v2
      with:
        name: workspace
        path: catkin_ws
        if-no-files-found: error
  build:
    needs: clone
    runs-on: ubuntu-latest
    container:
      image: ${{ matrix.images }}
    strategy:
      matrix:
        images: ['ros:noetic-perception', 'ros:melodic-perception', 'ros:foxy-ros-base']
        # compiler: ["/usr/bin/g++", "/usr/bin/clang++"]
    steps:
    - name: 'Install dependencies'
      shell: bash
      run: |
        apt update
        apt install -y \
          libusb-1.0-0{,-dev} \
          python3-colcon-common-extensions # temp
          python3-rosdep
    - uses: actions/download-artifact@v2
      with:
        name: workspace
        path: catkin_ws
    - name: 'Cache hunter files'
      id: cache-hunter
      uses: actions/cache@v2
      with:
        path: ~/.hunter
        key: ${{ matrix.images }}-hunter
    - name: "Debug"
      run: |
        pwd
        ls -al .
        ls -al catkin_ws/src/${{ github.repository }}
    - name: 'Setup catkin'
      shell: bash
      run: |
        source /opt/ros/*/setup.bash
        cd catkin_ws
        rosdep init
        rosdep update
        rosdep install --from-paths src --ignore-src
        # catkin_init_workspace
    - name: 'Build and install'
      shell: bash
      run: |
        export PYTHONIOENCODING=utf8  # from github.com/docker/compose/issues/2576
        source /opt/ros/*/setup.bash
        cd catkin_ws
        colcon build
        # catkin_make_isolated --install
    - name: 'Source and confirm'
      shell: bash
      run: |
        source catkin_ws/install_isolated/setup.bash
        roscd
        pwd  # TODO: put an assert on it
